### PR TITLE
Documentation for New ASDPlasticMaterial

### PR DESCRIPTION
**Pull request by jaabell**
Adds documentation for the new ASDPlasticMaterial class. 

ASDPlasticMaterial implements a large family of constitutive models based on the classical theory of elastoplasticity. Users build new constitutive models by selecting the yield function, plastic-flow direction, elasticity law, and hardening models for the internal variables from several possible options for each component.

### CODE REVIEW

**Comment by mhscott** [comment]
Is `ASDPlasticMaterial` in the source code repository? Is the cart before the horse?

**Comment by jaabell** [comment]
Hi Michael. Not yet, and this is why I haven't merged (although I do want to draw attention to the fact this is coming in soon). I'm getting ready to push the code into the main OpenSees branch, but I'm making sure it compiles on Windows. Then we'll need to get @fmckenna 's ok with the location of the new dependencies this will place on OpenSees and his overall opinion on the design.

**Comment by silviamazzoni** [comment]
@mhscott, as long as we don't pull the cart before the horse!

**Comment by jaabell** [comment]
Thanks @silviamazzoni and Michael. Feel free to let me know if you see something wrong with this before I or someone else merges .

**Pull request merged**
