### PR TITLE
- IMK model documentation revision

### PR DESCRIPTION
**Pull request by amaelkady**

### CODE REVIEW

**Comment by amaelkady** [comment]
Updated contact info for updated IMK models

**Comment by siwalan** [comment]
@amaelkady There is a merge conflict for this commit. This is because few months ago I reorganized the uniaxialMaterial folder (Putting materials in their own category, e.g. concrete mat has it own folder etc). You might want to update your branch from main or directly move the files.

**Comment by silviamazzoni** [comment]
I honestly don't think we should be making material categories...... materials are not actual "materials" they are just models! where would IMK go?

**Comment by siwalan** [comment]
@silviamazzoni The change is only in the interal .rst folder for the uniaxial material. At this current (and future state), there is almost hundred of .rst file and other files at that folder, making it very messy. 

For the end user, there is no 'material categories' or any visible change, i.e. the end user will still see https://opensees.github.io/OpenSeesDocumentation/user/manual/material/uniaxialMaterial.html as usual. The internal folder division would also help with figures/photo organization, since currently every figures etc is dumped on either the uniaxialMaterial/figures or directly inside the uniaxialMaterial folder. Hopefully, by having uniaxialMaterial/concrete, the figures file could be better managed.

For the internal .rst folder, I followed the subsection used in the https://opensees.github.io/OpenSeesDocumentation/user/manual/material/uniaxialMaterial.html and OpenSees Wiki, that is 'Other Uniaxial Material'.

**Comment by mhscott** [comment]
The documentation should follow the same directory structure as the SRC/ folders.

**Comment by silviamazzoni** [comment]
@mhscott , you read my mind! :)

**Comment by siwalan** [comment]
@silviamazzoni materials and model command is on a separate chapter/folder since, AFAIK, this repo init. This is not a choice that I make. Aside from that, the rest of the folder structure in this repo inherits from the OpenSeesWiki. If the documentation... want to be reorganized in accordance with the src/ folder of OpenSees, it can be done. But it would require significant rework in the ToC (e.g. having recorder folder in source root etc).
image


Thank you for your concern.

**Pull request closed without merging**
