### PR TITLE
Adding MEFI element documentation

### PR DESCRIPTION
**Pull request by carloslopezolea**
This PR adds documentation for the MEFI element.
https://github.com/OpenSees/OpenSees/pull/1315

### CODE REVIEW

**Comment by fmckenna** [comment]
An example is needed and also the sections to test the material per your last comment on your commit to the code repo.

**Comment by carloslopezolea** [comment]
Hi Frank!

I just updated the element documentation to include a pushover example for a RC wall that also performs a test comparing the expected and computed base shear.

Regards,
Carlos.

**Comment by carloslopezolea** [comment]
For the order of magnitude of the problem, a force unbalance tolerance of 100 is not high (we are using units of N, mm), although it can be reduced. To improve the slow convergence of the gravity loading phase, I recommend removing the -initial flag from Newton's algorithm. I will update the example to remove the -initial flag and reduce the tolerance for the gravity loading phase.

**Comment by mhscott** [comment]
Still pretty slow convergence for gravity loads with regular Newton.
image

**Comment by mhscott** [comment]
Also pretty high residual norms when using convergence test on displacement increment during pushover.
image

**Comment by carloslopezolea** [comment]
Hi Michael,

I think the residual norms are fine. If we do the same example using the SFI-MVLEM with FSAM material we get higher residual norms (see attached figure). 

image

Furthermore, if we compare using the E-SFI element (which I uploaded some time ago) with the FSAM material, we still get higher residual norms than the MEFI with RCLMS.

During this week the materials will be updated with the suggested modifications.
Regards.

**Pull request merged**
