### PR TITLE
ASDConcrete1D documentation

### PR DESCRIPTION
**Pull request by MassimoPetracca**
documentation for PR OpenSees/OpenSees#1449

### CODE REVIEW

**Comment by silviamazzoni** [comment]
Can you, please, provide more examples of response -- subjecting it to different cyclic load patterns in both tension and compression.

**Comment by MassimoPetracca** [comment]
Sure Silvia, I'll extend soon the documentation also showing some interesting results that can be extracted as Damage, Plastic Strain and crack width

**Comment by MassimoPetracca** [comment]
Hi @silviamazzoni, I just updated the documentation adding more examples

**Comment by silviamazzoni** [comment]
@MassimoPetracca thank you for the additional work. I recommend replacing the animated gifs with a static one at the end of the loading pattern, maybe also showing the strain history. As they are, it is difficult to evaluate and consider because there is not enough time to visualize the full response. Would it also be helpful to give the input values for each case.

**Comment by MassimoPetracca** [comment]
@silviamazzoni done

**Pull request merged**
