### PR TITLE
Update miscCommands.rst

### PR DESCRIPTION
**Pull request by BijanSeif**
Hi, seems nodeCoord had been missed!

The added line, added the existing nodeCoord.rst to documentation and make html convert it correctly to html.

### CODE REVIEW

**Comment by BijanSeif** [comment]
Hi, I wanted to pull them in separated pulls but, after each push from my pc to my fork, I don't know why they add to my first pull! (Seems it is messy)

**Comment by siwalan** [comment]
You need to create a new branch so that any additional commit does not add to your original pull requests. In a very short way, Git pull request merges the branch, not the files.

**Comment by BijanSeif** [comment]
> You need to create a new branch so that any additional commit does not add to your original pull requests. In a very short way, Git pull request merges the branch, not the files.

Thanks @siwalan for guidance. Now I will check it.

**Comment by BijanSeif** [comment]
@siwalan look at my last activity in the above. I created a branch [OpenSeesDocBranch](https://github.com/OpenSees/OpenSeesDocumentation/pull/89/commits/377f178cb42b7effbc17f8137e6081a33fc721bf) and then add a new pull, but again it has been added to the current pull!
Did I do something wrong?

**Comment by siwalan** [comment]
I would try to summarize:
1) You created a pull request to the main (or master, but let's use the term main) branch of OpenSeesDocs from your fork's main branch.
2) As long there pull request isn't merged by the OpenSeesDocs, any changes your master branch will be also included in your pull request. Any changes to your main branch after the pull request is accepted will not be merged/tracked in this pull request.
3) You created a new branch in your fork, and then **merged/pushed the updates from your new branch to your main branch**. Your changes is then 'pushed' to your pull request.

My suggestion
1) Create a new branch and then update at that branch only.
2) If you want to merge it to the OpenSeesDocs main repo, create a pull request between your **new** branch and the main OpenSeesDocs repo.

**Pull request merged**
